app = "jew-store"
primary_region = "waw"

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://tdjqqixszveiqtenpiug.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkanFxaXhzenZlaXF0ZW5waXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MTI1NTYsImV4cCI6MjA4ODk4ODU1Nn0.e6JDpA0EwiHy_g31xKUfsnwHiAxs6Aw6Hfrr_a7knm0"
    NEXT_PUBLIC_R2_PUBLIC_URL = "https://pub-fd10be2c2db14283890207e027f3cbe5.r2.dev"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
